<script setup lang="ts">
import {computed,reactive,ref} from "vue";
type Sheet={id:string;number:string;title:string;custom_properties:Record<string,string>}; type Subset={id:string;name:string;sheets:Sheet[]};
type Workspace={id:string;revision_id:string;sheet_set:{name:string;sheet_count:number;subset_count:number;custom_properties:Record<string,string>;subsets:Subset[]};diagnostics:{severity:string;code:string;message:string}[]}; type Job={id:string;status:string;progress:number;error_code?:string};
const dstPath=ref(""),workspace=ref<Workspace|null>(null),selected=ref<Subset|null>(null),error=ref(""); const commands=ref<Record<string,unknown>[]>([]),preview=ref<Record<string,any>|null>(null),job=ref<Job|null>(null),revisions=ref<Record<string,unknown>[]>([]);
const insertForm=reactive({number:"",title:"",sourceType:"template_layout",sourceFile:"",sourceLayout:"",position:0});
async function request(url:string,options?:RequestInit){const response=await fetch(url,{headers:{"Content-Type":"application/json"},...options});const body=await response.json();if(!response.ok)throw new Error(body.message??body.detail??"请求失败");return body}
async function openWorkspace(){try{workspace.value=await request("/api/workspaces/open",{method:"POST",body:JSON.stringify({dst_path:dstPath.value})});selected.value=workspace.value!.sheet_set.subsets[0]??null;commands.value=[];preview.value=null;job.value=null;error.value=""}catch(e){error.value=String(e)}}
function queueUpdate(sheet:Sheet){commands.value.push({type:"update_sheet",sheet_id:sheet.id,number:sheet.number,title:sheet.title,custom_properties:sheet.custom_properties})}
function queueSheetSet(){if(workspace.value)commands.value.push({type:"update_sheet_set",name:workspace.value.sheet_set.name,custom_properties:workspace.value.sheet_set.custom_properties})}
function queueSubset(delta=0){if(!workspace.value||!selected.value)return;const position=workspace.value.sheet_set.subsets.findIndex(item=>item.id===selected.value!.id);commands.value.push({type:"update_subset",subset_id:selected.value.id,name:selected.value.name,position:Math.max(0,Math.min(workspace.value.sheet_set.subsets.length-1,position+delta))})}
function queueReorder(sheet:Sheet,delta:number){if(!selected.value)return;const index=selected.value.sheets.findIndex(item=>item.id===sheet.id);commands.value.push({type:"reorder_sheet",sheet_id:sheet.id,position:Math.max(0,Math.min(selected.value.sheets.length-1,index+delta))})}
function queueDelete(sheet:Sheet){if(selected.value&&confirm(`删除图纸 ${sheet.number}？`))commands.value.push({type:"delete_sheet",sheet_id:sheet.id,delete_empty_subset:selected.value.sheets.length===1})}
function queueMove(sheet:Sheet,event:Event){const target=(event.target as HTMLSelectElement).value;if(!target||target===selected.value?.id)return;commands.value.push({type:"move_sheet",sheet_id:sheet.id,target_subset_id:target,position:workspace.value?.sheet_set.subsets.find(item=>item.id===target)?.sheets.length??0,delete_empty_source_subset:selected.value?.sheets.length===1})}
function queueInsert(){if(!selected.value||!insertForm.number||!insertForm.title||!insertForm.sourceFile||!insertForm.sourceLayout){error.value="新增图纸必须填写图号、标题、来源文件和来源布局";return}commands.value.push({type:"insert_sheet",target_subset_id:selected.value.id,position:insertForm.position,number:insertForm.number,title:insertForm.title,source:{type:insertForm.sourceType,file:insertForm.sourceFile,layout:insertForm.sourceLayout}});error.value=""}
async function showPreview(){if(workspace.value)preview.value=await request(`/api/workspaces/${workspace.value.id}/changes/preview`,{method:"POST",body:JSON.stringify({base_revision_id:workspace.value.revision_id,commands:commands.value})})}
async function execute(){if(!workspace.value||!preview.value||!confirm("确认发布？原DST和受影响DWG将永久备份。"))return;job.value=await request(`/api/workspaces/${workspace.value.id}/changes/execute`,{method:"POST",body:JSON.stringify({base_revision_id:workspace.value.revision_id,commands:commands.value,cad_version:"2020"})});if(job.value?.status==="QUEUED")watchJob(job.value.id);else if(job.value?.status==="SUCCEEDED")await openWorkspace()}
function watchJob(id:string){const events=new EventSource(`/api/jobs/${id}/events`);events.onmessage=async event=>{job.value=JSON.parse(event.data);if(["SUCCEEDED","FAILED","ROLLED_BACK","BLOCKED_FILE_LOCK"].includes(job.value!.status)){events.close();if(job.value!.status==="SUCCEEDED")await openWorkspace()}};events.onerror=()=>events.close()}
async function loadRevisions(){revisions.value=await request("/api/revisions")} const blocking=computed(()=>workspace.value?.diagnostics.filter(item=>item.severity==="error")??[]);
</script>
<template><header><h1>DST Manager</h1><span>MVP · 本地文件事务</span></header><main><section class="open"><input v-model="dstPath" placeholder="输入 .dst 绝对路径" @keyup.enter="openWorkspace"><button @click="openWorkspace">打开项目</button><button @click="loadRevisions">修订历史</button></section><p v-if="error" class="error">{{error}}</p><section v-if="job" class="job"><b>任务 {{job.id}}</b><span>{{job.status}} · {{job.progress}}%</span><span v-if="job.error_code" class="error">{{job.error_code}}</span></section><section v-if="revisions.length" class="preview"><h2>永久修订</h2><pre>{{JSON.stringify(revisions,null,2)}}</pre></section>
<template v-if="workspace"><section class="summary"><div><small>图纸集</small><input v-model="workspace.sheet_set.name"><button @click="queueSheetSet">更新图纸集</button></div><div><small>子集</small><strong>{{workspace.sheet_set.subset_count}}</strong></div><div><small>图纸</small><strong>{{workspace.sheet_set.sheet_count}}</strong></div><div><small>阻断诊断</small><strong>{{blocking.length}}</strong></div></section><details v-if="Object.keys(workspace.sheet_set.custom_properties).length"><summary>图纸集自定义属性</summary><label v-for="(_,name) in workspace.sheet_set.custom_properties" :key="name">{{name}}<input v-model="workspace.sheet_set.custom_properties[name]"></label><button @click="queueSheetSet">加入属性变更</button></details><details v-if="workspace.diagnostics.length"><summary>诊断（{{workspace.diagnostics.length}}）</summary><ul><li v-for="item in workspace.diagnostics" :key="item.code+item.message" :class="item.severity">{{item.code}}：{{item.message}}</li></ul></details>
<section class="editor"><aside><button v-for="subset in workspace.sheet_set.subsets" :key="subset.id" :class="{active:selected?.id===subset.id}" @click="selected=subset">{{subset.name}} <b>{{subset.sheets.length}}</b></button></aside><article><div class="toolbar"><input v-if="selected" v-model="selected.name"><button @click="queueSubset(-1)">子集↑</button><button @click="queueSubset(1)">子集↓</button><button @click="queueSubset()">更新子集</button><span>待处理 {{commands.length}}</span><button :disabled="!commands.length" @click="commands=[];preview=null">清空</button><button :disabled="!commands.length" @click="showPreview">预览变更</button></div><table><thead><tr><th>图号</th><th>标题/自定义属性</th><th>排序</th><th>移动到</th><th></th></tr></thead><tbody><tr v-for="sheet in selected?.sheets" :key="sheet.id"><td><input v-model="sheet.number"></td><td><input v-model="sheet.title"><details v-if="Object.keys(sheet.custom_properties).length"><summary>自定义属性</summary><label v-for="(_,name) in sheet.custom_properties" :key="name">{{name}}<input v-model="sheet.custom_properties[name]"></label></details></td><td><button @click="queueReorder(sheet,-1)">↑</button><button @click="queueReorder(sheet,1)">↓</button></td><td><select @change="queueMove(sheet,$event)"><option value="">选择子集</option><option v-for="subset in workspace.sheet_set.subsets" :key="subset.id" :value="subset.id" :disabled="subset.id===selected?.id">{{subset.name}}</option></select></td><td><button @click="queueUpdate(sheet)">更新</button><button class="danger" @click="queueDelete(sheet)">删除</button></td></tr></tbody></table>
<fieldset><legend>新增图纸</legend><input v-model="insertForm.number" placeholder="图号"><input v-model="insertForm.title" placeholder="标题"><select v-model="insertForm.sourceType"><option value="template_layout">DWG/DWT模板布局</option><option value="existing_snapshot">已有布局</option></select><input v-model="insertForm.sourceFile" placeholder="来源DWG/DWT绝对路径"><input v-model="insertForm.sourceLayout" placeholder="来源布局名"><input v-model.number="insertForm.position" type="number" min="0" :max="selected?.sheets.length??0"><button @click="queueInsert">加入新增命令</button></fieldset></article></section><section v-if="preview" class="preview"><h2>完整变更预览</h2><pre>{{JSON.stringify(preview,null,2)}}</pre><button class="primary" :disabled="preview.executable===false" @click="execute">确认并执行</button></section></template></main></template>
